//! Simple proof generator for the value-setter-zk module
//!
//! This is a development tool for generating mock proofs for testing purposes.
//! In a production environment, you would use RISC0's proving system with a
//! proper guest program.
//!
//! Usage:
//!   cargo run --example proof_generator -- <value>
//!
//! This will output a JSON proof payload that can be used in a transaction.

use sov_value_setter_zk::ValueSetterZkProofPayload;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    
    if args.len() != 2 {
        eprintln!("Usage: {} <value>", args[0]);
        eprintln!("Example: {} 42", args[0]);
        std::process::exit(1);
    }
    
    let value: u32 = args[1].parse().expect("Value must be a valid u32");
    
    // Generate a mock proof
    // In production, this would be generated by RISC0
    let proof = generate_mock_proof(value);
    
    // Output as JSON
    let json = serde_json::to_string_pretty(&proof).expect("Failed to serialize proof");
    println!("{}", json);
}

/// Generates a mock proof for testing purposes.
///
/// **WARNING**: This is NOT a real RISC0 proof and will only work if you've
/// installed a mock verifier in your test environment. For production use,
/// you need to generate real RISC0 proofs using a guest program.
fn generate_mock_proof(value: u32) -> ValueSetterZkProofPayload {
    ValueSetterZkProofPayload {
        // Mock method ID (all zeros)
        // In production, this would be the actual RISC0 method ID
        method_id: [0u8; 32],
        // Encode the value as the "proof" for mock purposes
        // In production, this would be the actual RISC0 proof bytes
        proof: value.to_le_bytes().to_vec(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_mock_proof() {
        let value = 42;
        let proof = generate_mock_proof(value);
        
        assert_eq!(proof.method_id, [0u8; 32]);
        assert_eq!(proof.proof, vec![42, 0, 0, 0]);
    }
}

